################################################################
## Music follow you with the presence based on BLE
################################################################
homeassistant:
automation:
  - alias: only_bedroom_playing
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.jkq
        to: '房间'
        for:
          seconds: 20
    condition:
      - condition: state
        entity_id: media_player.main_controller
        state: playing
    action:
      - service: media_player.volume_mute
        data:
          entity_id:
            - media_player.snapcast_client_00253102e69e
            - media_player.snapcast_client_00253105f3a8
          is_volume_muted: true

  - alias: bedroom_not_playing
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.jkq
        to: '厨房'
        for:
          seconds: 20
     - platform: state
        entity_id: sensor.jkq
        to: '厕所'
        for:
          seconds: 20
    condition:
      - condition: state
        entity_id: media_player.main_controller
        state: playing
    action:
      - service: media_player.volume_mute
        data:
          entity_id:
            - media_player.snapcast_client_00253102e69e
          is_volume_muted: true
          
  - alias: turn_on_wwd
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.wwd
        state: on
    action:  
      - service: media_player.select_source
        entity_id: media_player.main_controller
        source: '11'
  - alias: turn_on_cjfx
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.cjfx
        state: on
    action:  
      - service: media_player.select_source
        entity_id: media_player.main_controller
        source: 'cjfx'
#- service: media_player.play_media
#data:
#entity_id: media_player.main_controller
#media_content_id: http://91.121.134.23:8100/stream
#media_content_type: 'mp3'
      
      - wait_template: >-
          {{ is_state('input_select.alarm_clock', 'Disabled') }}
        timeout: '00:00:20'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: 0.2

      - wait_template: >-
          {{ is_state('input_select.alarm_clock', 'Disabled') }}
        timeout: '00:01:00'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: 0.3
      
      - service: media_player.media_stop
        data:
          entity_id: media_player.bedroom
      
      - service: tts.amazon_polly_say
        data_template:
          entity_id: media_player.bedroom
          message: >
              Good morning.
              The forecast for today is {{states.sensor.dark_sky_hourly_summary.state}}
              {% if states.sensor.netatmo_rain_gauge_sum_rain_1.state | float > 0 %}
                It has been raining in the last hour.
              {% endif %}
              The current temperature is {{states.sensor.netatmo_outside_temperature.state}}{{states.sensor.netatmo_outside_temperature.attributes.unit_of_measurement}}
              {% if states.sensor.netatmo_outside_min_temp.state | int < 3 %}
                The overnight low was {{states.sensor.netatmo_outside_min_temp.state }} so be careful for ice when you are driving.
              {% endif %}
              {% if states.sensor.dark_sky_visibility.state | int < 2 %}
                Please be aware that visibility is currently poor.
              {% endif %}
      - wait_template: "{{ states.media_player.bedroom.state == 'idle' }}"

      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: 0.2
      
      - service: media_player.play_media
        data:
          entity_id: media_player.bedroom
          media_content_id: http://91.121.134.23:8100/stream
          media_content_type: 'audio/mp4'

      - wait_template: >-
          {{ is_state('input_select.alarm_clock', 'Disabled') }}
        timeout: '00:00:20'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: 0.2

      - wait_template: >-
          {{ is_state('input_select.alarm_clock', 'Disabled') }}
        timeout: '00:00:20'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: 0.3

      - wait_template: >-
          {{ is_state('input_select.alarm_clock', 'Disabled') }}
        timeout: '00:00:20'
      - service: media_player.volume_set
        data:
          entity_id: media_player.bedroom
          volume_level: 0.4

      - wait_template: >-
          {{ is_state('input_select.alarm_clock', 'Disabled') }}
        timeout: '01:00:00'
      
      - service: media_player.turn_off
        data:
          entity_id:
            - media_player.bedroom
#################################################################
## Media Players

media_player:
  - platform: mpd
    name: 'Mopidy'
    host: REDACTED.253

#################################################################
## Groups
group:

  mopidy_main:
    entities:
      - media_player.mopidy

  playlist_control:
    name: Playlist Control
    control: hidden
    entities:
    - input_select.playlist_content
    - input_select.playlist_source
    - script.playlist_remote

#################################################################
## Inputs

input_select:
  playlist_content:
    name: 'Content:'
    options:
      - Michigan Radio
      - Dinner
      - Jazz
      - Chicago Blues
      - USER1's Favorites
    icon: mdi:playlist-play

  playlist_source:
    name: 'Source:'
    options:
      - Kitchen Stereo
      - Bedside Speaker
      - Living Room TV
      - Bedside/Stereo Speakers
    initial: Kitchen Stereo
    icon: mdi:speaker-wireless

#################################################################
## Scripts
script:

  playlist_action:
    sequence:

      - service: media_player.play_media
        data_template:
          entity_id: media_player.mopidy
          media_content_type: 'audio/mp4'
          media_content_id: >
            {% if is_state("input_select.playlist_content", "Michigan Radio") %} tunein:station:s23407
            {% elif is_state("input_select.playlist_content", "Dinner") %} spotify:user:REDACTED
            {% elif is_state("input_select.playlist_content", "Jazz") %} spotify:user:REDACTED
            {% elif is_state("input_select.playlist_content", "Chicago Blues") %} REDACTED
            {% elif is_state("input_select.playlist_content", "USER1's Favorites") %} spotify:user:REDACTED
            {% endif %}
      - delay: "00:00:01"
      - service: media_player.play_media
        data_template:
          media_content_id: 'http://REDACTED.253:8000/mopidy.mp3'
          media_content_type: 'audio/mp4'
          entity_id: >
            {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.kitchen_stereo
            {% elif is_state("input_select.playlist_source", "Bedside Speaker") %} media_player.bedside_speaker
            {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
            {% elif is_state("input_select.playlist_source", "Bedside/Stereo Speakers") %} media_player.bedsidestereo_speakers
            {% endif %}
  playlist_volup:
    sequence:
      service: media_player.volume_up
      data_template:
        entity_id: >
          {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.kitchen_stereo
          {% elif is_state("input_select.playlist_source", "Bedside Speaker") %} media_player.bedside_speaker
          {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
          {% elif is_state("input_select.playlist_source", "Bedside/Stereo Speakers") %} media_player.bedsidestereo_speakers
          {% endif %}
  playlist_voldown:
    sequence:
      service: media_player.volume_down
      data_template:
        entity_id: >
          {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.kitchen_stereo
          {% elif is_state("input_select.playlist_source", "Bedside Speaker") %} media_player.bedside_speaker
          {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
          {% elif is_state("input_select.playlist_source", "Bedside/Stereo Speakers") %} media_player.bedsidestereo_speakers
          {% endif %}
  playlist_stop:
    sequence:
      - service: homeassistant.turn_off
        entity_id: media_player.mopidy
      - service: homeassistant.turn_off
        data_template:
          entity_id: >
            {% if is_state("input_select.playlist_source", "Kitchen Stereo") %} media_player.kitchen_stereo
            {% elif is_state("input_select.playlist_source", "Bedside Speaker") %} media_player.bedside_speaker
            {% elif is_state("input_select.playlist_source", "Living Room TV") %} media_player.living_room_tv
            {% elif is_state("input_select.playlist_source", "Bedside/Stereo Speakers") %} media_player.bedsidestereo_speakers
            {% endif %}
#################################################################
## Automations
automation:

  # Turn off Mopidy when not in use
  - alias: Mopidy turn off

    trigger:
      - platform: state
        entity_id: media_player.kitchen_stereo
        to: 'off'
      - platform: state
        entity_id: media_player.bedside_speaker
        to: 'off'
      - platform: state
        entity_id: media_player.living_room_tv
        to: 'off'
      - platform: state
        entity_id: media_player.bedsidestereo_speakers
        to: 'off'

    condition:
      condition: and
      conditions:
        - condition: state
          entity_id: media_player.kitchen_stereo
          state: 'off'
        - condition: state
          entity_id: media_player.bedside_speaker
          state: 'off'
        - condition: state
          entity_id: media_player.living_room_tv
          state: 'off'
        - condition: state
          entity_id: media_player.bedsidestereo_speakers
          state: 'off'

    action:
      - service: homeassistant.turn_off
        entity_id: media_player.mopidy

  # Mopidy Visable
  - alias: Mopidy visable true

    trigger:
      platform: template
      value_template: "{{ not is_state('media_player.mopidy', 'off') }}"

    action:
      service: group.set_visibility
      entity_id: group.mopidy_main
      data:
        visible: True

  - alias: Mopidy visable false

    trigger:
      - platform: homeassistant
        event: start
      - platform: state
        entity_id: media_player.mopidy
        to: 'off'

    action:
      service: group.set_visibility
      entity_id: group.mopidy_main
      data:
        visible: False
