################################################################
## Follow Music with the presence based on BLE
################################################################
homeassistant:
automation:
  - alias: only_bedroom_playing
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.jhh
        to: '房间'
        for:
          seconds: 20
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{states.media_player.main_controller.attributes.source=='11' or states.media_player.main_controller.attributes.source=='cjfx' or states.media_player.main_controller.attributes.source=='lsd' or states.media_player.main_controller.attributes.source=='hdxzd' }}"
        - condition: state
          entity_id: media_player.main_controller
          state: 'playing'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id:
            - media_player.snapcast_client_7277a1e
            - media_player.snapcast_client_00253105f3a8
            - media_player.snapcast_client_00253102e69e
          volume_level: '{{ states.media_player.main_controller.attributes.volume_level }}'
      - service: media_player.volume_mute
        data:
          entity_id:
            - media_player.snapcast_client_7277a1e
            - media_player.snapcast_client_00253105f3a8
          is_volume_muted: true

  - alias: bedroom_not_playing
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.jkq
        to: '厨房'
        for:
          seconds: 20
      - platform: state
        entity_id: sensor.jkq
        to: '厕所'
        for:
          seconds: 20
    condition:
      condition: and
      conditions:
        - condition: template
          value_template: "{{states.media_player.main_controller.attributes.source=='11' or states.media_player.main_controller.attributes.source=='cjfx' or states.media_player.main_controller.attributes.source=='lsd' or states.media_player.main_controller.attributes.source=='hdxzd' }}"
        - condition: state
          entity_id: media_player.main_controller
          state: 'playing'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id:
            - media_player.snapcast_client_7277a1e
            - media_player.snapcast_client_00253105f3a8
            - media_player.snapcast_client_00253102e69e
          volume_level: '{{ states.media_player.main_controller.attributes.volume_level }}'
      - service: media_player.volume_mute
        data:
          entity_id:
            - media_player.snapcast_client_00253102e69e
          is_volume_muted: true
  - alias: restore_volume_when_playing
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: media_player.main_controller
        to: 'playing'
    condition:
        - condition: template
          value_template: "{{states.media_player.main_controller.attributes.source==''}}"
    action:
      - service: media_player.volume_set
        data_template:
          entity_id:
            - media_player.snapcast_client_7277a1e
            - media_player.snapcast_client_00253105f3a8
            - media_player.snapcast_client_00253102e69e
          volume_level: '{{ states.media_player.main_controller.attributes.volume_level }}'
##########################################################
# Standard IR remote to Control MPD 
##########################################################
  - alias: turn_on_wwd
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "home/IRtoMQTT"
        payload: '33737269'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.main_controller
          source: '11'
  - alias: turn_on_cjfx
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "home/IRtoMQTT"
        payload: '33741349'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.main_controller
          source: 'cjfx'
  - alias: turn_on_lsd
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "home/IRtoMQTT"
        payload: '33745429'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.main_controller
          source: 'lsd'
  - alias: turn_on_hdxzd
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "home/IRtoMQTT"
        payload: '33696469'
    action:
      - service: media_player.select_source
        data:
          entity_id: media_player.main_controller
          source: 'hdxzd'
  - alias: volume_up_mpd
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "home/IRtoMQTT"
        payload: '33738799'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.main_controller
          volume_level: '{{ states.media_player.main_controller.attributes.volume_level | int + 0.1 }}'
  - alias: volume_down_mpd
    initial_state: 'on'
    trigger:
      - platform: mqtt
        topic: "home/IRtoMQTT"
        payload: '33714319'
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.main_controller
          volume_level: '{{ states.media_player.main_controller.attributes.volume_level | int - 0.1 }}'
  - alias: 'MPD_Play_Pause'
    trigger:
      platform: mqtt
      topic: "home/IRtoMQTT"
      payload: '33730639'
    action:
#      service_template:
#        {% if is_state('media_player.main_controller','playing') %}
#          media_player.media_pause
#        {% else %}
#          media_player.media_play
#        {% endif %}
      service: media_player.media_play_pause
      entity_id: media_player.main_controller
  - alias: 'MPD_Previous'
    trigger:
      platform: mqtt
      topic: "home/IRtoMQTT"
      payload: '33687799'
    action:
      service: media_player.media_previous_track
      entity_id: media_player.main_controller
  - alias: 'MPD_Next'
    trigger:
      platform: mqtt
      topic: "home/IRtoMQTT"
      payload: '33720439'
    action:
      service: media_player.media_next_track
      entity_id: media_player.main_controller
#############################################################
#- service: media_player.play_media
#data:
#entity_id: media_player.main_controller
#media_content_id: http://91.121.134.23:8100/stream
#media_content_type: 'mp3'
